name: run web.py

on:
  push:
  schedule:
     - cron: '0 0 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: checkout repo content
        uses: actions/checkout@v2 # checkout the repository content

      - name: setup node
        uses: actions/setup-node@v2 # setup node

      - name: install dependencies
        run: npm install

      - name: execute generate.js script
        run: node generate.js

      # commit results to repository
      - name: Commit results
        run: |
          git config --local user.email "joe@artlung.com"
          git config --local user.name "artlung"
          git add index.html
          git add *.json
          git add *.xml
          git commit -m "Update results"
          git push
